import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Al Zaaffran Family Reataurant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="/Restaurantly/assets/vendor/animate.css/animate.min.css" rel="stylesheet" />
        <link href="/Restaurantly/assets/vendor/aos/aos.css" rel="stylesheet" />
        <link href="/Restaurantly/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="/Restaurantly/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
        <link href="/Restaurantly/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" />
        <link href="/Restaurantly/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet" />
        <link href="/Restaurantly/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet" />
        <link href="/Restaurantly/assets/css/style.css" rel="stylesheet" />

      </head>
      <body>{children}


        {/* <div id="preloader"></div> */}
        <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

        <script src="/Restaurantly/assets/vendor/aos/aos.js"></script>
        <script src="/Restaurantly/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="/Restaurantly/assets/vendor/glightbox/js/glightbox.min.js"></script>
        <script src="/Restaurantly/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
        <script src="/Restaurantly/assets/vendor/swiper/swiper-bundle.min.js"></script>
        <script src="/Restaurantly/assets/vendor/php-email-form/validate.js"></script>
        <script src="/Restaurantly/assets/js/main.js"></script>
      </body>
    </html>
  );
}
